spring:
  datasource:
    username: cylin
    password: Abcd1234!
    url: jdbc:mysql://127.0.0.1:3306/standard_seminar_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml