spring:
  datasource:
    username: root
    url: jdbc:mysql://47.107.54.231:3306/standard_seminar_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    password: 12345678
  mail:
    username: 1010410164@qq.com
    password: shibfaeqmqkrbfgg
    host: smtp.qq.com
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名转换
  type-aliases-package: com.rest.entity
server:
  port: 8080